spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vdt_live
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

file:
  upload-dir: ./uploads

jwt:
  expiration: 86400000
