name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - production
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - production
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('backend/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2      
      - name: Run tests
        working-directory: ./backend
        run: mvn clean test
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          STREAM_URL_BASE: ${{ secrets.STREAM_URL_BASE }}      
      - name: Build with Maven
        working-directory: ./backend
        run: mvn clean package -DskipTests
        env:
          MAVEN_OPTS: -Dmaven.repo.local=~/.m2/repository
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          SPRING_JPA_HIBERNATE_DDL_AUTO: ${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          STREAM_URL_BASE: ${{ secrets.STREAM_URL_BASE }}      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: backend/target/*.jar
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.ref == 'refs/heads/production'
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App using CLI
        run: |
          # Get the JAR file name
          JAR_FILE=$(ls *.jar | head -n 1)
          echo "Deploying JAR file: $JAR_FILE"
          
          # Deploy using Azure CLI
          az webapp deploy \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --src-path $JAR_FILE \
            --type jar \
            --async false
          
          echo "Deployment completed successfully"

      - name: Set App Settings
        run: |
          az webapp config appsettings set \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --settings \
              SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}" \
              SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}" \
              SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}" \
              SPRING_JPA_HIBERNATE_DDL_AUTO="${{ secrets.SPRING_JPA_HIBERNATE_DDL_AUTO }}" \
              SERVER_PORT="${{ secrets.SERVER_PORT }}" \
              STREAM_URL_BASE="${{ secrets.STREAM_URL_BASE }}"

      - name: Restart App Service
        run: |
          az webapp restart \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_WEBAPP_NAME }}
          
          echo "App Service restarted successfully"
